version: "3.6"

services:

  device_interoperability_ms:
    # Building the image
    <<: &device_interoperability_ms
      image: "device_interoperability_ms:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "10007:10007"
    env_file: 
      - env_file